<?php



/**
 * Skeleton subclass for representing a row from the 'sf_extranet_item' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Thu May 31 08:16:10 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfExtranetPlugin.lib.model
 */
class sfExtranetItem extends BasesfExtranetItem {

	public function isDocument()
	{
		return $this->getType() == 'document';
	}

	public function isEvent()
	{
		return $this->getType() == 'event';
	}

	public function getAuthor()
	{
		$anonymous = sfConfig::get('app_extranet_anonymous_name', sfConfig::get('extranet_anonymous_name'));
		if ($this->getCreatedBy())
		{
			$author = $this->getsfGuardUser()->getProfile()->getFullName();
		}

		return isset($author) ? $author : $anonymous;
	}

} // sfExtranetItem
