<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_extranet_item' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Thu May 31 08:16:10 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfExtranetPlugin.lib.model
 */
class sfExtranetEventPeer extends sfExtranetItemPeer {

} // sfExtranetItemPeer
